---
- name: Install Docker CE on RHEL
  hosts: localhost
  gather_facts: no
  become: yes

  tasks:

    - name: Remove conflicting Podman and Buildah packages
      ansible.builtin.dnf:
        name:
          - podman
          - buildah
          - docker
          - docker-client
          - docker-client-latest
          - docker-common
          - docker-latest
          - docker-latest-logrotate
          - docker-logrotate
          - docker-engine
          - runc
        state: absent

    - name: Enable DNF Plugins Core
      ansible.builtin.dnf: 
        name: dnf-plugins-core
        state: present

    - name: Add a custom DNF repository
      ansible.builtin.yum_repository:
        name: Docker-Repo 
        description: DockerCE
        baseurl: https://download.docker.com/linux/rhel/$releasever/$basearch/stable
        enabled: true
        gpgcheck: true
        gpgkey: https://download.docker.com/linux/rhel/gpg

    - name: Installing Docker Packages 
      ansible.builtin.dnf:
        name:
          - docker-ce 
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present

    - name: Enable and Start Docker 
      ansible.builtin.service: 
        name: docker
        state: started
        enabled: yes
