---
- name: Zabbix Installation Script
  gather_facts: true
  hosts: all
  become: true

  vars: 
    zabbix_server: "{{ server | default('') }}"
    zabbix_hostname: "{{ host | default('') }}"
    config_file: "/etc/zabbix/zabbix_agent2.conf"

  tasks:
# -------------------------------------------------------------------------
# Pre-checks and Validation
# -------------------------------------------------------------------------

    - name: Check if Zabbix Configuration File exists
      ansible.builtin.stat: 
        path: "{{ config_file }}"
      register: file_check

    - name: Ansible File Found - exit 
      ansible.builtin.debug: 
        msg: "File found. Exiting."
      when: file_check.stat.exists

    - name: Stop Play-Book if file exists 
      ansible.builtin.meta: end_play
      when: file_check.stat.exists
      no_log: true # Supressing output task message

# -------------------------------------------------------------------------
# Adding Repos & Package Installation 
# -------------------------------------------------------------------------
    - name: Install GPG Keys
      ansible.builtin.command:
        cmd: "rpm --import {{ item }}"
      loop: 
        - https://repo.zabbix.com/RPM-GPG-KEY-ZABBIX-08EFA7DD
        - https://repo.zabbix.com/RPM-GPG-KEY-ZABBIX-B5333005
        
      when: ansible_os_family == "RedHat"

    - name: Adding Repos to the Various Linux
      block:

# RHEL repo

        - name: Adding Zabbix Repo to RHEL
          ansible.builtin.dnf:
            name: https://repo.zabbix.com/zabbix/7.4/release/rhel/{{ ansible_distribution_major_version }}/noarch/zabbix-release-latest-7.4.el{{ ansible_distribution_major_version }}.noarch.rpm
            state: present 
          when: ansible_distribution == "RedHat"

# Rocky repo

        - name: Adding Zabbix Repo to Rocky
          ansible.builtin.dnf:
           name: https://repo.zabbix.com/zabbix/7.4/release/rocky/{{ ansible_distribution_major_version }}/noarch/zabbix-release-latest-7.4.el{{ ansible_distribution_major_version }}.noarch.rpm
           state: present 
          when: ansible_distribution == "Rocky"

# Alma Linux repo

        - name: Adding Zabbix Repo to Alma Linux 
          ansible.builtin.dnf:
           name: https://repo.zabbix.com/zabbix/7.4/release/alma/{{ ansible_distribution_major_version }}/noarch/zabbix-release-latest-7.4.el{{ ansible_distribution_major_version }}.noarch.rpm
           state: present 
          when: ansible_distribution == "AlmaLinux"

# CentsOS repo

        - name: Adding Zabbix Repo to CentOS 
          ansible.builtin.dnf:
           name: https://repo.zabbix.com/zabbix/7.4/release/centos/{{ ansible_distribution_major_version }}/noarch/zabbix-release-latest-7.4.el{{ ansible_distribution_major_version }}.noarch.rpm
           state: present 
          when: ansible_distribution == "CentOS"

# -------------------------------------------------------------------------
# Installing Zabbix  
# -------------------------------------------------------------------------

    - name: Install Zabbix Agent 2
      ansible.builtin.dnf:
        name: zabbix-agent2
        state: present
        #disablerepo: "pgdg*"
      when: ansible_os_family == "RedHat"
    
# -------------------------------------------------------------------------
# Firewall Configuration
# -------------------------------------------------------------------------

    - name: Populate service facts
      ansible.builtin.service_facts:
    
    - name: Allow TCP port 10050 in firewalld immediately and permanently
      ansible.builtin.command:
        cmd: firewall-cmd --permanent --zone=public --add-port=10050/tcp
      register: firewall_result
      changed_when: "'ALREADY_ENABLED' not in firewall_result.stderr"
      when:
        - ansible_facts.services['firewalld.service'] is defined
        - ansible_facts.services['firewalld.service'].state == 'running'

    - name: Reload Firewalld
      ansible.builtin.command:
        cmd: firewall-cmd --reload
      register: firewall_result
      changed_when: "'ALREADY_ENABLED' not in firewall_result.stderr"
      when:
        - ansible_facts.services['firewalld.service'] is defined
        - ansible_facts.services['firewalld.service'].state == 'running'
    # -------------------------------------------------------------------------
    # Making Changes to the configuration file
    # -------------------------------------------------------------------------
    
    - name: Check if 'server' and 'host' contain actual text content
      ansible.builtin.assert:
        that:
          - zabbix_server is defined and (zabbix_server | string | trim | length > 0)
          - zabbix_hostname is defined and (zabbix_hostname | string | trim | length > 0)
        fail_msg: >- 
          ERROR: Missing required arguments!

    - name: Editing config file via Ansible
      ansible.builtin.lineinfile:
        path: "{{ config_file }}"
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      loop:
        - { regexp: '^#?\s*Server=.*', line: "Server={{ zabbix_server }}" }
        - { regexp: '^#?\s*ServerActive=.*', line: "ServerActive={{ zabbix_server }}" }
        - { regexp: '^#?\s*Hostname=.*', line: "Hostname={{ zabbix_hostname }}" }

    # -------------------------------------------------------------------------
    # Service Management
    # -------------------------------------------------------------------------
    
    - name: Enable and start Zabbix Agent 2 service
      ansible.builtin.systemd:
        name: zabbix-agent2
        state: started
        enabled: true
        daemon_reload: true
...